In [0]:
import numpy as np
import torch

# Numpy와 함께 배우는 PyTorch 기본 문법 
- Numpy와 PyTorch는 상당히 비슷한 syntax를 갖고 있음.
- 분석 과정에서 두 패키지의 자료형 간 변환이 잦기 때문에 같이 알고 있으면 좋음.


## What are tensors?
![](https://uploads-ssl.webflow.com/5b1d427ae0c922e912eda447/5cd99a73f8ce4494ad86852e_arraychart.jpg)

## Constructors

In [0]:
np.zeros?

In [0]:
torch.zeros?

In [4]:
# Creating a 3 x 3 matrix with zeros
shape=(3, 3)
zeros_pt = torch.zeros(shape)
zeros_np = np.zeros(shape)
print(zeros_pt)
print(zeros_np)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [0]:
np.ones?

In [0]:
torch.ones?

In [7]:
# Creating a 2 x 5 matrix with ones
shape = (2, 5)
ones_pt = torch.ones(shape)
ones_np = np.ones(shape)
print(ones_pt)
print(ones_np)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [0]:
np.eye?

In [0]:
torch.eye?

In [10]:
# Creating a 4 x 4 identity matrix
size = 4
eye_pt = torch.eye(size)
eye_np = np.eye(size)
print(eye_pt)
print(eye_np)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [0]:
np.random.normal?

In [0]:
torch.randn?

In [13]:
# Randomly sample 5 values from normal distribution with mean 0 and variance 1.
normal_pt = torch.randn(5)
normal_np = np.random.normal(size=5)
print(normal_pt)
print(normal_np)

tensor([-0.6776,  2.8302,  0.4785,  0.9407,  0.3396])
[ 0.62960693 -0.93276301  0.40466182  0.07721321  0.53582524]


## From existing data

In [0]:
isinstance?

In [15]:
# Python list
data = list(range(10))
assert isinstance(data, list)
print(data)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [0]:
np.array?

In [0]:
torch.tensor?

In [18]:
# python list -> numpy array
data_np = np.array(data, dtype=np.float32)
assert isinstance(data_np, np.ndarray)
print(data_np)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [19]:
# python list -> torch tensor
data_pt = torch.tensor(data)
assert isinstance(data_pt, torch.Tensor)
print(data_pt)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [0]:
torch.from_numpy?

In [21]:
# numpy array -> torch tensor
data_pt = torch.from_numpy(data_np)
assert isinstance(data_pt, torch.Tensor)
print(data_pt)

tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])


In [0]:
torch.Tensor.numpy?

In [23]:
# torch tensor -> numpy array
data_np = data_pt.numpy()
assert isinstance(data_np, np.ndarray)
print(data_np)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [0]:
np.copy?

In [25]:
# (numpy) copy data
a = np.zeros(3)
b = a.copy()
b += np.ones_like(a)
print('a:', a)
print('b:', b)

a: [0. 0. 0.]
b: [1. 1. 1.]


In [0]:
torch.Tensor.clone?

In [27]:
# (pytorch) copy data
c = torch.ones(4)
d = c.clone()
d += torch.ones_like(c)
print('c:', c)
print('d:', d)

c: tensor([1., 1., 1., 1.])
d: tensor([2., 2., 2., 2.])


## Numerical ranges

In [0]:
range?

In [0]:
np.arange?

In [0]:
torch.arange?

In [31]:
size = 10
a = list(range(size))
b = np.arange(size)
c = torch.arange(size)
print(a, '\n', b, '\n', c)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] 
 [0 1 2 3 4 5 6 7 8 9] 
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [32]:
start = 0
end = 20
step = 2
a = list(range(start, end, step))
b = np.arange(start, end, step)
c = torch.arange(start, end, step)
print(a, '\n', b, '\n', c)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18] 
 [ 0  2  4  6  8 10 12 14 16 18] 
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])


## Linear algebra

In [0]:
np.matmul?

In [0]:
np.dot?

In [35]:
# numpy
a = np.ones((1, 3))
b = np.ones((3, 4))
c = np.matmul(a, b)  # method 1
d = np.dot(a, b)     # method 2
print('c:', c)
print('d:', d)

c: [[3. 3. 3. 3.]]
d: [[3. 3. 3. 3.]]


In [0]:
torch.mm?

In [37]:
# pytorch
a = torch.ones(1, 3)
b = torch.ones(3, 4)
c = torch.mm(a, b)
print(c)

tensor([[3., 3., 3., 3.]])


## Attributes

In [0]:
shape = (2, 6)
a = np.ones(shape)
b = torch.ones(shape)

In [39]:
# Check shape
print(a.shape)
print(b.shape)   # method 1
print(b.size())  # method 2

(2, 6)
torch.Size([2, 6])
torch.Size([2, 6])


In [40]:
# Check dtype
print(a.dtype)
print(b.dtype)

float64
torch.float32


In [41]:
# Check size
print(a.ndim)
print(b.dim())

2
2


## Indexing

In [42]:
# Create a numpy array and copy a torch tensor
a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]], dtype=np.float32)
b = torch.from_numpy(a)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [43]:
# Get first row
print(a[0])
print(b[0])

[1. 2. 3.]
tensor([1., 2., 3.])


In [44]:
# Get first & third rows
print(a[[0, 2]])
print(b[[0, 2]])

[[1. 2. 3.]
 [7. 8. 9.]]
tensor([[1., 2., 3.],
        [7., 8., 9.]])


In [45]:
# Get second column
print(a[:, 1])
print(b[:, 1])

[2. 5. 8.]
tensor([2., 5., 8.])


In [46]:
# By boolean indices
print(a[a > 3])
print(b[b > 3])

[4. 5. 6. 7. 8. 9.]
tensor([4., 5., 6., 7., 8., 9.])


## Shape manipulation

In [47]:
# Create a torch tensor and copy a numpy array
b = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
a = b.numpy()
print(a)
print('Shape:', a.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
Shape: (2, 3)


In [0]:
np.ndarray.flatten?

In [0]:
torch.Tensor.view?

In [50]:
# (2, 3) -> (6, ); flatten
c = a.flatten()
d = b.view(-1)
print(c, c.shape)
print(d, d.size())

[1. 2. 3. 4. 5. 6.] (6,)
tensor([1., 2., 3., 4., 5., 6.]) torch.Size([6])


In [0]:
np.reshape?

In [0]:
torch.reshape?

In [53]:
# (2, 3) -> (1, 6)
new_shape = (1, 6)
c = a.reshape(new_shape)  # numpy
d = b.reshape(new_shape)  # torch; method 1
e = b.view(new_shape)     # torch; method 2
print(c,  c.shape)
print(d,  d.shape)
print(e,  e.size())

[[1. 2. 3. 4. 5. 6.]] (1, 6)
tensor([[1., 2., 3., 4., 5., 6.]]) torch.Size([1, 6])
tensor([[1., 2., 3., 4., 5., 6.]]) torch.Size([1, 6])


In [0]:
np.expand_dims?

In [0]:
torch.unsqueeze?

In [56]:
# add new dimension (2, 3) -> (1, 2, 3)
c = np.expand_dims(a, axis=0)
print(c, '\nshape change: {} -> {}'.format(a.shape, c.shape))

print('-' * 9)

d = b.unsqueeze(0)
print(d, '\nshape change: {} -> {}'.format(b.shape, d.shape))

[[[1. 2. 3.]
  [4. 5. 6.]]] 
shape change: (2, 3) -> (1, 2, 3)
---------
tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) 
shape change: torch.Size([2, 3]) -> torch.Size([1, 2, 3])


In [0]:
np.squeeze?

In [58]:
# (numpy) remove redundant dimension; (2, 1, 4) -> (2, 4)
shape = (2, 1, 4)
a = np.arange(8).reshape(shape)
c = a.squeeze(1)  # remove first dimension

print('Shape change: {} -> {}'.format(a.shape, c.shape))

Shape change: (2, 1, 4) -> (2, 4)


In [0]:
torch.squeeze?

In [60]:
# (pytorch) remove redundant dimension; (2, 3, 4, 1) -> (2, 3, 4)
shape = (2, 3, 4, 1)
b = torch.arange(24).view(shape)
d = b.squeeze(3)   # method 1; select 3rd dimension
e = b.squeeze(-1)  # method 2; select last dimension

assert d.size() == e.size()

print('Shape change: {} -> {}'.format(b.size(), d.size()))

Shape change: torch.Size([2, 3, 4, 1]) -> torch.Size([2, 3, 4])


In [0]:
np.transpose?

In [0]:
torch.transpose?

In [63]:
# Transpose
shape = (2, 3, 7)
a = np.zeros(shape)
b = torch.from_numpy(a)

c = a.transpose([1, 0, 2])
d = b.transpose(0, 1)

print(c.shape)
print(d.size())

(3, 2, 7)
torch.Size([3, 2, 7])


## Item selection and manipulation

In [0]:
np.repeat?

In [0]:
torch.Tensor.repeat?

In [66]:
# repeat acts differently!
a = np.array([1, 2, 3], dtype=np.int32)
b = torch.from_numpy(a)

print(a.repeat(2))
print(b.repeat(2))

[1 1 2 2 3 3]
tensor([1, 2, 3, 1, 2, 3], dtype=torch.int32)


In [0]:
np.tile?

In [68]:
# Tile
a = np.array([1, 2, 3]).reshape(1, -1)
b = torch.from_numpy(a)

c = np.tile(a, (2, 4))
print('Numpy tile:\n', c.shape, '\n', c)

print('-')

d = b.repeat(2, 4)
print('Pytorch tile:\n', d.shape, '\n', d)

Numpy tile:
 (2, 12) 
 [[1 2 3 1 2 3 1 2 3 1 2 3]
 [1 2 3 1 2 3 1 2 3 1 2 3]]
-
Pytorch tile:
 torch.Size([2, 12]) 
 tensor([[1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3],
        [1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3]])


In [0]:
np.sort?

In [0]:
np.argsort?

In [0]:
torch.Tensor.repeat?

In [72]:
# sorting
b = torch.tensor([10, 6, 32, 4, 21])
a = b.numpy()

sorted_a = np.sort(a)
sorting_ind_a = np.argsort(a)
sorted_b, sorting_ind_b = torch.sort(b, descending=False)

print('Sorted values: ', sorted_a, sorted_b)
print('Sorting indices: ', sorting_ind_a, sorting_ind_b)

Sorted values:  [ 4  6 10 21 32] tensor([ 4,  6, 10, 21, 32])
Sorting indices:  [3 1 0 4 2] tensor([3, 1, 0, 4, 2])


## Arithmetics

In [73]:
b = torch.tensor([[1, 3, 5], [2, 1, 7]], dtype=torch.float32)
a = b.numpy()
print(b)

tensor([[1., 3., 5.],
        [2., 1., 7.]])


In [74]:
# reducing to a single value
print(a.min(), a.max())
print(b.min(), b.max())

1.0 7.0
tensor(1.) tensor(7.)


In [75]:
# (numpy) reducing along zero dimension
a.max(axis=0)

array([2., 3., 7.], dtype=float32)

In [76]:
# (torch) reducing along zero dimension; returns values and indices
b.max(dim=0)

torch.return_types.max(values=tensor([2., 3., 7.]), indices=tensor([1, 0, 1]))

In [77]:
# (torch) reducing along first dimension; returns value and indices
b.max(dim=1)

torch.return_types.max(values=tensor([5., 7.]), indices=tensor([2, 2]))

In [78]:
# (torch) average over all values
b.mean()

tensor(3.1667)

In [79]:
# (torch) average over dim 0
b.mean(dim=0)

tensor([1.5000, 2.0000, 6.0000])

In [80]:
# torch) average over dim 1
b.mean(dim=1)

tensor([3.0000, 3.3333])